### PR TITLE
🧑‍💻 generate bitcoin script performance report during test execution instead of simple print

### PR DESCRIPTION
**Pull request by AbdelStark**
# Description 

Generate a report to track the performance of the various Bitcoin scripts generated during the execution of tests.

# Changes summary
- Create `test_utils/report` module to add utility functions to generate and manage a CSV report file
- Update tests to invoke the report function instead of printing
- Update the Test CI to upload the report as downloadable artifact

Example of generated file:
Screenshot 2024-05-31 at 16 04 39

### CODE REVIEW

**Review by weikengchen — APPROVED** [review]

**Comment by weikengchen** [comment]
Approved. Can merge if it is ready.

**Comment by weikengchen** [comment]
(do not have to be in this PR though)

**Comment by AbdelStark** [comment]
> does it mean that we should replace the performance "table" (it is just a simple list) in the current README with a link to the rendered report?

Yes i believe so

**Comment by AbdelStark** [comment]
> (do not have to be in this PR though)

Ok let's do that in a follow up PR. I will try to come up with something cool. Perhaps auto generate in the doc site.

**Comment by AbdelStark** [comment]
> does it mean that we should replace the performance "table" (it is just a simple list) in the current README with a link to the rendered report?

Maybe we can put a link to the catgolfing ?
https://catgolfing.btcwild.life/
It displays the table with the latest report dynamically.

**Pull request merged**
